### ISSUE TITLE
Fails to launch IE via IEDriverServer 3.9, IE1, W10 x64

### ISSUE THREAD

**Issue by mandibt** [eagleEggs/EHX#4]
Fails to launch Internet Explorer 11 on Windows 10 x64. IEDriverServer version 3.9

Please check

**Comment by eagleEggs** [comment]
For reference I have tested on 32bit IEDriverServer on IE11 Windows 10 x64.

Will be interesting to see what's causing this issue. I figured there would be many different environments, will have to do some further testing with various versions and I'll get it worked out.

**Comment by eagleEggs** [comment]
Does this driver version work in your scripts when opening IE11? I tested with a few other drivers and they work great, but 3.9 doesn't seem to work at all with IE11. Is there a reason you need to use 3.9 instead of getting a newer version?

Version Repository::
http://selenium-release.storage.googleapis.com/index.html

**Comment by eagleEggs** [comment]
Were you able to get try a newer version of the Selenium driver?

**Comment by eagleEggs** [comment]
Hey let me know how you're doing. I'll close this issue Monday but feel free to reach back out if you need further assistance :D
